# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-29T00:35:51+00:00

from __future__ import annotations

from enum import Enum
from typing import List, Optional

from pydantic import BaseModel, Field


class AbusiveStatus(Enum):
    UNKNOWN = 'UNKNOWN'
    PASSING = 'PASSING'
    FAILING = 'FAILING'


class FilterStatus(Enum):
    UNKNOWN = 'UNKNOWN'
    ON = 'ON'
    OFF = 'OFF'
    PAUSED = 'PAUSED'
    PENDING = 'PENDING'


class SiteSummaryResponse(BaseModel):
    abusiveStatus: Optional[AbusiveStatus] = Field(
        None, description="The site's Abusive Experience Report status."
    )
    enforcementTime: Optional[str] = Field(
        None,
        description='The time at which [enforcement](https://support.google.com/webtools/answer/7538608) against the site began or will begin. Not set when the filter_status is OFF.',
    )
    filterStatus: Optional[FilterStatus] = Field(
        None,
        description="The site's [enforcement status](https://support.google.com/webtools/answer/7538608).",
    )
    lastChangeTime: Optional[str] = Field(
        None, description="The time at which the site's status last changed."
    )
    reportUrl: Optional[str] = Field(
        None,
        description='A link to the full Abusive Experience Report for the site. Not set in ViolatingSitesResponse. Note that you must complete the [Search Console verification process](https://support.google.com/webmasters/answer/9008080) for the site before you can access the full report.',
    )
    reviewedSite: Optional[str] = Field(
        None, description='The name of the reviewed site, e.g. `google.com`.'
    )
    underReview: Optional[bool] = Field(
        None, description='Whether the site is currently under review.'
    )


class ViolatingSitesResponse(BaseModel):
    violatingSites: Optional[List[SiteSummaryResponse]] = Field(
        None, description='The list of violating sites.'
    )


class FieldXgafv(Enum):
    field_1 = '1'
    field_2 = '2'


class Alt(Enum):
    json = 'json'
    media = 'media'
    proto = 'proto'
